[tool.poetry]
name = "shopping_basket"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Istvan Agardi <username@example.org>"]
license = ""

[tool.poetry.dependencies]
python = "^3.9.13"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"
flake8 = "^3.8.4"
mypy = "^0.960"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
