@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(communityUser, "CommunityUser", "Radio Station Listener")

System_Boundary(radioStation, "Radio station") {
    Person(radioDj, "DJ", "Radio station DJ on air")
    Container(containerAlias, "Label", "Technology", "Optional Description")
    System(systemAlias, "Label", "Optional Description")
}

Rel(radioDj, containerAlias, "Label", "Optional Technology")
Rel(communityUser, containerAlias, "Label", "Optional Technology")
@enduml